version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566" # Porta padrão para o LocalStack
    environment:
      - SERVICES=rds
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: aurora_db
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  localstack_data:
  mysql_data:

